- name: Build Execution
  env:
    LLVM_SYS_160_PREFIX: ${{ matrix.llvm_path }}
  run: |
    # Flutter 前置操作
    flutter precache --force
    dart pub global activate flutter_rust_bridge_codegen

    # 修复代码生成器路径引用
    flutter_rust_bridge_codegen \
      --rust-input lib/src/ffi.rs \
      --dart-output lib/generated/bridge.dart \
      --llvm-path "${{ matrix.llvm_path }}"

    # 修复构建脚本执行方式（显式调用解释器）
    case "${{ matrix.os }}" in
      windows-2022)
        pwsh -Command "./scripts/${{ matrix.build_script }}" `
          --target "${{ matrix.rust_target }}" `
          --release-type "${{ inputs.release_type }}"
        ;;
      *)
        bash "./scripts/${{ matrix.build_script }}" \
          --target "${{ matrix.rust_target }}" \
          --release-type "${{ inputs.release_type }}"
        ;;
    esac
