 
 name: Build Execution
on:
  # 手动触发配置
  workflow_dispatch:
    inputs:
      build-mode:
        description: '选择构建模式'
        required: true
        type: choice
        options:
          - debug
          - release
        default: 'release'
      clean-cache:
        description: '清除构建缓存'
        type: boolean
        default: false

  # 自动触发配置
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

 

  run: |
    # Flutter 前置操作
    flutter precache --force
    dart pub global activate flutter_rust_bridge_codegen

    # 修复代码生成器路径引用
    flutter_rust_bridge_codegen \
      --rust-input lib/src/ffi.rs \
      --dart-output lib/generated/bridge.dart \
      --llvm-path "${{ matrix.llvm_path }}"

    # 修复构建脚本执行方式（显式调用解释器）
    case "${{ matrix.os }}" in
      windows-2022)
        pwsh -Command "./scripts/${{ matrix.build_script }}" `
          --target "${{ matrix.rust_target }}" `
          --release-type "${{ inputs.release_type }}"
        ;;
      *)
        bash "./scripts/${{ matrix.build_script }}" \
          --target "${{ matrix.rust_target }}" \
          --release-type "${{ inputs.release_type }}"
        ;;
    esac
